#!/bin/bash
# Source the other important files (and add to this as the repo grows)
# We want the functionality included by these files here
source $HOME/.bash/alias
source $HOME/.bash/functions
source $HOME/.bash/path
source $HOME/.bash/prompt.bash

# This files commands go here

# Initialize ansible
[ -d $HOME/.ansible ] && source $HOME/.ansible/hacking/env-setup > /dev/null 2>&1

# Enable completion for non-system bash
[ -f $HOME/.git-completion.bash ] && source $HOME/.git-completion.bash

# environment variables
export EDITOR=vim

# Local configs should override everything
[ -f $HOME/.bash/localrc ] && source $HOME/.bash/localrc
