#!/bin/bash
# Custom bash functions

psclone() { git clone ps-bitbucket:predictivescience/$1; }

mkd() { mkdir $@; cd $@; }
cdl() { cd "$@" && ls; }

docks() {
    case $1 in
        "up")
            machine=${2-default}
            docker-machine up $machine
            echo "Docker machine started"
            eval `docker-machine env $machine`
            echo "Environment configured"
            ;;
        *)
            echo "Usage: docks [up] args"
            ;;
    esac
    exit 0
}
