#!/bin/bash
# Custom bash functions

psclone() { git clone ps-bitbucket:predictivescience/$1; }

mkd() { mkdir $@; cd $@; }
cdl() { cd "$@" && ls; }

docks() {
    machine=${1:-default}
    state=$(docker-machine status ${machine})
    if [ ${state} != "Running" ]; then
        echo "Docker machine ${machine} is not running.  Starting..."
        docker-machine start ${machine} 2>&1 > /dev/null
    fi
    echo "Configuring shell to use docker machine ${machine}..."
    eval `docker-machine env ${machine}`
}
