[project]
name = "dotfiles"
version = "0.1.0"
description = "cderwin's dotfiles and tools to manage bootstrapping a new machine"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attrs>=25.4.0",
    "click>=8.3.0",
]
