# Source the other important files (and add to this as the repo grows)
# We want the functionality included by these files here
source $HOME/.bash/alias
source $HOME/.bash/functions
source $HOME/.bash/path
source $HOME/.bash/prompt.zsh

# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

. "$HOME/.asdf/asdf.sh"

# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/cderwin/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/cderwin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/cderwin/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/cderwin/google-cloud-sdk/completion.zsh.inc'; fi

# environment variables
export EDITOR=vim

# Local configs should override everything
[ -f $HOME/.bash/localrc ] && source $HOME/.bash/localrc
